server:
  port: 8801

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: wang0804
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com:
      ynthm:
        demo:
          mybatis:
            tk:
              user:
                mapper: debug
mybatis:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql
