# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###
POST {{baseUrl}}/auth/test
Content-Type: application/json

{
  "messageType": "11"
}

###

GET {{baseUrl}}/users/test
Accept: application/json

{
  "messageType": "1"
}

###
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "999",
  "email": "content",
  "mobile": "123123"
}

###
POST {{baseUrl}}/auth/code
Content-Type: application/json

{
  "areaCode": "86",
  "phoneNumber": "18588207723"
}

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "areaCode": "86",
  "phoneNumber": "11",
  "password": "12345678",
  "confirmPassword": "12345678",
  "verificationCode": "888888"
}

###