server:
  port: 9401
  error:
    include-message: always
spring:
  application:
    name: wb-cross-login
  profiles:
    active: dev
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:cross-login.db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      #      data-locations: classpath:sql/data.sql
      encoding: UTF-8
      mode: always
      continue-on-error: true

okhttp:
  connect-timeout: 1
  read-timeout: 3
  write-timeout: 3
  # 连接池中整体的空闲连接的最大数量
  max-idle-connections: 200
  # 连接空闲时间最多为 300 秒
  keep-alive-duration: 300