server:
  port: 8100
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?rewriteBatchedStatements=true
    username: root
    password: wang0804
    hikari:
      data-source-properties:
        useConfigs: maxPerformance
        rewriteBatchedStatements: true
  jdbc:
    template:
      max-rows: 1000
  sql:
    init:
      schema-locations: classpath*:schema-all.sql
      username: root
      password: wang0804
