server:
  port: 8888
  http2:
    enabled: true
  shutdown: graceful
  forward-headers-strategy: native

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: wang0804
    driver-class-name: com.mysql.cj.jdbc.Driver

  lifecycle:
    timeout-per-shutdown-phase: 10s
  profiles:
    active: @profile.env@
  servlet:
    multipart:
      max-request-size: 64MB
      max-file-size: 16MB
  output:
    ansi:
      enabled: always