# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 上传KYC文件
POST {{baseUrl}}/agents/kyc/files
Authorization: {{auth_token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="idFront"; filename="idFront.jpeg"

< /Users/ethan/Downloads/@large.jpeg
--boundary
Content-Disposition: form-data; name="idBack"; filename="idBack.jpeg"

< /Users/ethan/Downloads/@large.jpeg
--boundary--

> {%
    client.global.set("file_id_front", response.body.data.idFront);
%}

###
# 查看图片
GET {{baseUrl}}/fs/{{file_id_front}}
Authorization: {{auth_token}}


###