server:
  port: 8801
  shutdown: graceful

spring:
  application:
    name: web-demo
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:8900
        instance:
          name: web-demo
#  jackson:
#    time-zone: GMT+8
local.ssl:
  trust-store: classpath:ynthm-truststore.jks
  trust-store-password: changeit

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true