server:
  port: 8900
  shutdown: graceful
spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: root
    password: wang0804
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect