server:
  port: 8803
  shutdown: graceful
  ssl:
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.3
    key-store: classpath:keystore.p12
    key-store-password: changeit
    trust-store: classpath:ynthm-truststore.jks
    trust-store-password: changeit


spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test
    username: root
    password: wang0804
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
