server:
  port: 8803
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/security-demo
    username: root
    password: wang0804
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true